spring:
  application:
    name: cloud-trpc-server
  sleuth:
    sampler:
      percentage: 1
    scheduled:
      enabled: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

server:
  port: 0
trpc:
  server:
    port: 9090

ratelimit:
  enabled: true
  server: GRPC
  default-policy: #optional - will apply unless specific policy exists
    limit: 3 #optional - request number limit per refresh interval window
    quota: 1000 #optional - request time limit per refresh interval window (in seconds)
    refresh-interval: 60 #default value (in seconds)
    type: origin
  policies:
    sayHello:
      limit: 3 #optional - request number limit per refresh interval window
      quota: 1000 #optional - request time limit per refresh interval window (in seconds)
      refresh-interval: 60 #default value (in seconds)
      type: origin

# eureka配置
#spring:
#  application:
#    name: cloud-grpc-server
#  sleuth:
#    sampler:
#      percentage: 1
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}